config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tenants
  resources :users

  resources :properties

  controller :sessions do
    get 'login' => :new, as: :login
    post 'login' => :create
    delete 'logout' => :destroy, as: :logout
  end

  root 'sessions#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tenant.rb
# frozen_string_literal: true

class Tenant < ApplicationRecord
  FIRST_NAME_MAX_LENGTH = 100
  LAST_NAME_MAX_LENGTH = 100
  EMAIL_MAX_LENGTH = 200

  # rubocop:disable Layout/LineLength
  EMAIL_REGEX = /\A([a-z0-9\+_\-\']+)(\.[a-z0-9\+_\-\']+)*@([a-z0-9\-]+\.)+[a-z]{2,6}\z/ix.freeze
  # rubocop:enable Layout/LineLength

  before_validation :downcase
  before_validation :strip_whitespace

  validates :email, presence: true
  validates :email, length: { maximum: EMAIL_MAX_LENGTH,
                              if: :email }
  validates :email, format: { with: EMAIL_REGEX },
                    if: -> { errors[:email].blank? }

  validates :first_name, presence: true
  validates :first_name, length: { maximum: FIRST_NAME_MAX_LENGTH,
                                   if: :first_name }
  validates :first_name, number_of_lines: { maximum: 1 },
                         if: -> { errors[:first_name].blank? }

  validates :last_name, presence: true
  validates :last_name, length: { maximum: LAST_NAME_MAX_LENGTH,
                                  if: :last_name }
  validates :last_name, number_of_lines: { maximum: 1 },
                        if: -> { errors[:last_name].blank? }

  private

  def strip_whitespace
    email&.strip!
    first_name&.strip!
    last_name&.strip!
  end

  def downcase
    email&.downcase!
  end
end

app/controllers/tenants_controller.rb
# frozen_string_literal: true

class TenantsController < ApplicationController
  before_action :set_tenant, only: %i[show edit update destroy]

  def index
    @tenants = Tenant.all
  end

  def show; end

  def new
    @tenant = Tenant.new
  end

  def edit; end

  def create
    @tenant = Tenant.new(tenant_params)

    if @tenant.save
      flash[:success] = I18n.t(:success_create,
                               scope: 'controllers.tenants.messages',
                               first_name: @tenant.first_name,
                               last_name: @tenant.last_name)

      redirect_to @tenant
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @tenant.update(tenant_params)
      flash[:success] = I18n.t(:success_update,
                               scope: 'controllers.tenants.messages',
                               first_name: @tenant.first_name,
                               last_name: @tenant.last_name)

      redirect_to @tenant
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tenant.destroy

    redirect_to tenants_url, notice: 'Tenant was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tenant
    @tenant = Tenant.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tenant_params
    params.require(:tenant).permit(:first_name, :last_name, :email)
  end
end

app/helpers/tenants_helper.rb
# frozen_string_literal: true

module TenantsHelper
end

app/views/tenants/_form.html.erb
<%= form_with(model: tenant, local: true) do |form| %>
  <div class="field">
    <%= form.label :first_name %>
    
    <%= form.text_field :first_name %>

    <% if tenant.errors[:first_name] %>
      <% tenant.errors[:first_name].each do |message| %>
        <p class="errorMessage">
          <%= message %>
        </p>
      <% end %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :last_name %>

    <%= form.text_field :last_name %>

    <% if tenant.errors[:last_name] %>
      <% tenant.errors[:last_name].each do |message| %>
        <p class="errorMessage">
          <%= message %>
        </p>
      <% end %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :email %>

    <%= form.text_field :email %>

    <% if tenant.errors[:email] %>
      <% tenant.errors[:email].each do |message| %>
        <p class="errorMessage">
          <%= message %>
        </p>
      <% end %>
    <% end %>
  </div>

  <div class="actions">
    <% if tenant.persisted? %>
      <button type="submit" name="commit" class="addButton">
        <i class="fa fa-floppy-o" aria-hidden="true"></i>Update Tenant
      </button>

      <%= link_to '<i class="fa fa-times-circle" aria-hidden="true"></i>Cancel'.html_safe, tenant, class: "destroyButton" %>
    <% else %>
      <button type="submit" name="commit" class="addButton">
        <i class="fa fa-floppy-o" aria-hidden="true"></i>Create Tenant
      </button>
      <%= link_to '<i class="fa fa-times-circle" aria-hidden="true"></i>Cancel'.html_safe, tenants_path, class: "destroyButton" %>
    <% end %>
  </div>
<% end %>

app/views/tenants/edit.html.erb
<section class='scaffold'>
  <h2 class="breadcrumbs">
    <%= link_to "Tenants", tenants_path %>
    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
    <%= link_to "#{@tenant.first_name} #{@tenant.last_name}", @tenant %>
    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
    Edit
  </h2>

    <%= render "form", tenant: @tenant %>
</section>

app/views/tenants/index.html.erb
<section class='scaffold'>
  <h2 class="breadcrumbs">Tenants</h2>

  <p>
    <%= link_to '<i class="fa fa-plus-circle" aria-hidden="true"></i>New Tenant'.html_safe, new_tenant_path, class: "addButton" %>
  </p>

  <table class="scaffoldListTable">
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @tenants.each do |tenant| %>
        <tr>
          <td><%= link_to tenant.first_name, tenant %></td>
          <td><%= link_to tenant.last_name, tenant %></td>
          <td><%= link_to tenant.email, tenant %></td>
          <td><%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_tenant_path(tenant), title: "Edit Tenant" %></td>
          <td><%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, tenant, method: :delete, data: { confirm: "Are you sure want to delete #{tenant.first_name} #{tenant.last_name}?" }, title: "Delete Tenant" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

   <p>
    <%= link_to '<i class="fa fa-plus-circle" aria-hidden="true"></i>New Tenant'.html_safe, new_tenant_path, class: "addButton" %>
  </p>
</section>

app/views/tenants/new.html.erb
<section class='scaffold'>
  <h2 class="breadcrumbs">
    <%= link_to "Tenants", tenants_path %>
    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
    New Tenant
  </h2>

    <%= render "form", tenant: @tenant %>
</section>

app/views/tenants/show.html.erb
<section class='scaffold'>
  <h2 class="breadcrumbs">
    <%= link_to "Tenants", tenants_path %>
    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
    <%= @tenant.first_name %> <%= @tenant.last_name %>
  </h2>

  <p>
    <%= link_to '<i class="fa fa-plus-circle" aria-hidden="true"></i>New Tenant'.html_safe, new_tenant_path, class: "addButton" %>
  </p>

  
  <table class="scaffoldDataTable">
    <tbody>
      <tr>
        <th>First Name</th>

        <th>Last Name</th>

        <th>Email</th>

        <th>Created</th>

        <th>Last Updated</th>
      </tr>

      <tr>
        <td><%= @tenant.first_name %></td>
        
        <td><%= @tenant.last_name %></td>
        
        <td><%= @tenant.email %></td>

        <td><%= @tenant.created_at.strftime("%H:%M:%S %A %d %B %Y") %></td>

        <td><%= @tenant.updated_at.strftime("%H:%M:%S %A %d %B %Y") %></td>
      </tr>
    </tbody>
  </table>

  <p>
    <%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>Edit Tenant'.html_safe, edit_tenant_path(@tenant), class: "defaultButton" %>
  </p>
</section>