config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tenants
  resources :users

  resources :properties

  controller :sessions do
    get 'login' => :new, as: :login
    post 'login' => :create
    delete 'logout' => :destroy, as: :logout
  end

  root 'sessions#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/property.rb
# frozen_string_literal: true

class Property < ApplicationRecord
  PROPERTY_NAME_MAX_LENGTH = 100
  PROPERTY_ADDRESS_MAX_LENGTH = 500
  LANDLORD_FIRST_NAME_MAX_LENGTH = 100
  LANDLORD_LAST_NAME_MAX_LENGTH = 100
  LANDLORD_EMAIL_MAX_LENGTH = 200

  # rubocop:disable Layout/LineLength
  LANDLORD_EMAIL_REGEX = /\A([a-z0-9\+_\-\']+)(\.[a-z0-9\+_\-\']+)*@([a-z0-9\-]+\.)+[a-z]{2,6}\z/ix.freeze
  # rubocop:enable Layout/LineLength

  validates :property_name, presence: true
  validates :property_name, uniqueness: { case_sensitive: false }
  validates :property_name, length: { maximum: PROPERTY_NAME_MAX_LENGTH,
                                      if: :property_name }
  validates :property_address, presence: true
  validates :property_address, length: { maximum: PROPERTY_ADDRESS_MAX_LENGTH,
                                         if: :property_address }
  validates :landlord_first_name, presence: true
  validates :landlord_first_name, length: {
    maximum: LANDLORD_FIRST_NAME_MAX_LENGTH, if: :landlord_first_name
  }
  validates :landlord_last_name, presence: true
  validates :landlord_last_name, length: {
    maximum: LANDLORD_LAST_NAME_MAX_LENGTH, if: :landlord_last_name
  }
  validates :landlord_email, presence: true
  validates :landlord_email, length: { maximum: LANDLORD_EMAIL_MAX_LENGTH,
                                       if: :landlord_email }
  validates :landlord_email, format: { with: LANDLORD_EMAIL_REGEX },
                             if: -> { errors[:landlord_email].blank? }
end

app/controllers/properties_controller.rb
# frozen_string_literal: true

class PropertiesController < ApplicationController
  before_action :set_property, only: %i[show edit update destroy]

  def index
    @properties = Property.all
  end

  def show; end

  def new
    @property = Property.new
  end

  def edit; end

  def create
    @property = Property.new(property_params)

    if @property.save
      flash[:success] = 'Property was successfully created.'
      redirect_to @property
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @property.update(property_params)
      flash[:success] = 'Property was successfully updated.'
      redirect_to @property
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @property.destroy

    redirect_to properties_url, notice: 'Property was successfully destroyed.'
  end

  private

  def set_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(
      :property_name,
      :property_address,
      :landlord_first_name,
      :landlord_last_name,
      :landlord_email
    )
  end
end

app/helpers/properties_helper.rb
# frozen_string_literal: true

module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <div class="field">
    <%= form.label :property_name %>
    
    <%= form.text_field :property_name %>

    <% if property.errors[:property_name] %>
      <% property.errors[:property_name].each do |message| %>
        <p class="errorMessage">
          <%= message %>
        </p>
      <% end %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :property_address %>

    <%= form.text_area :property_address, rows: 10 %>

    <% if property.errors[:property_address] %>
      <% property.errors[:property_address].each do |message| %>
        <p class="errorMessage">
          <%= message %>
        </p>
      <% end %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :landlord_first_name %>

    <%= form.text_field :landlord_first_name %>

    <% if property.errors[:landlord_first_name] %>
      <% property.errors[:landlord_first_name].each do |message| %>
        <p class="errorMessage">
          <%= message %>
        </p>
      <% end %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :landlord_last_name %>

    <%= form.text_field :landlord_last_name %>

    <% if property.errors[:landlord_last_name] %>
      <% property.errors[:landlord_last_name].each do |message| %>
        <p class="errorMessage">
          <%= message %>
        </p>
      <% end %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :landlord_email %>

    <%= form.text_field :landlord_email %>

    <% if property.errors[:landlord_email] %>
      <% property.errors[:landlord_email].each do |message| %>
        <p class="errorMessage">
          <%= message %>
        </p>
      <% end %>
    <% end %>
  </div>

  <div class="actions">
    <% if property.persisted? %>
      <button type="submit" name="commit" class="addButton">
        <i class="fa fa-floppy-o" aria-hidden="true"></i>Update Property
      </button>

      <%= link_to '<i class="fa fa-times-circle" aria-hidden="true"></i>Cancel'.html_safe, property, class: "destroyButton" %>
    <% else %>
      <button type="submit" name="commit" class="addButton">
        <i class="fa fa-floppy-o" aria-hidden="true"></i>Create Property
      </button>
      <%= link_to '<i class="fa fa-times-circle" aria-hidden="true"></i>Cancel'.html_safe, properties_path, class: "destroyButton" %>
    <% end %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<section class='scaffold'>
  <h2 class="breadcrumbs">
    <%= link_to "Properties", properties_path %>
    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
    <%= link_to @property.property_name, @property %>
    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
    Edit
  </h2>

    <%= render "form", property: @property %>
</section>

app/views/properties/index.html.erb
<section class='scaffold'>
  <h2 class="breadcrumbs">Properties</h2>

  <p>
    <%= link_to '<i class="fa fa-plus-circle" aria-hidden="true"></i>New Property'.html_safe, new_property_path, class: "addButton" %>
  </p>

  <table class="scaffoldListTable">
    <thead>
      <tr>
        <th>Property name</th>
        <th>Property address</th>
        <th>Landlord first name</th>
        <th>Landlord last name</th>
        <th>Landlord email</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @properties.each do |property| %>
        <tr>
          <td><%= link_to property.property_name, property %></td>
          <td>
            <pre><%= property.property_address %></pre>
          </td>
          <td><%= property.landlord_first_name %></td>
          <td><%= property.landlord_last_name %></td>
          <td><%= property.landlord_email %></td>
          <td><%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_property_path(property), title: "Edit Property" %></td>
          <td><%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, property, method: :delete, data: { confirm: "Are you sure want to delete #{property.property_name}?" }, title: "Delete Property" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <p>
    <%= link_to '<i class="fa fa-plus-circle" aria-hidden="true"></i>New Property'.html_safe, new_property_path, class: "addButton" %>
  </p> 
</section>

app/views/properties/new.html.erb
<section class='scaffold'>
  <h2 class="breadcrumbs">
    <%= link_to "Properties", properties_path %>
    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
    New Property
  </h2>

    <%= render "form", property: @property %>
</section>

app/views/properties/show.html.erb
<section class='scaffold'>
  <h2 class="breadcrumbs">
    <%= link_to "Properties", properties_path %>
    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
    <%= @property.property_name %>
  </h2>

  <p>
    <%= link_to '<i class="fa fa-plus-circle" aria-hidden="true"></i>New Property'.html_safe, new_property_path, class: "addButton" %>
  </p>

  <table class="scaffoldDataTable">
    <tbody>
      <tr>
        <th>Property Name</th>

        <th>Property Address</th>

        <th>Created</th>

        <th>Last Updated</th>
      </tr>

      <tr>
        <td><%= @property.property_name %></td>

        <td>
          <pre><%= @property.property_address %></pre>
        </td>

        <td><%= @property.created_at.strftime("%H:%M:%S %A %d %B %Y") %></td>

        <td><%= @property.updated_at.strftime("%H:%M:%S %A %d %B %Y") %></td>
      </tr>

      <tr>
        <th>Landlord First Name</th>

        <th>Landlord Last Name</th>

        <th>Landlord Email</th>
      </tr>

       <tr>
        <td><%= @property.landlord_first_name %></td>

        <td><%= @property.landlord_last_name %></td>

        <td><%= @property.landlord_email %></td>
      </tr>
    </tbody>
  </table>

  <p>
    <%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>Edit Property'.html_safe, edit_property_path(@property), class: "defaultButton" %>
  </p>
</section>